AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LeBonCoinCoin Backend - Classified Ads Platform

Globals:
  Function:
    Timeout: 30
    MemorySize: 2048
    Runtime: java21
    Architectures:
      - x86_64
    Environment:
      Variables:
        QUARKUS_PROFILE: prod
        JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
        QUARKUS_HTTP_CORS_ENABLED: "false"
  HttpApi:
    CorsConfiguration:
      AllowCredentials: true
      AllowOrigins:
        - "http://localhost:5173"
        - "https://master.d1edk4x9k6kvah.amplifyapp.com"
        - "https://leboncoincoin.fr"
      AllowMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      AllowHeaders:
        - "*"
      MaxAge: 300

Parameters:
  DbUrl:
    Type: String
    Description: JDBC URL
  DbUsername:
    Type: String
  DbPassword:
    Type: String
    NoEcho: true
  ClerkClientId:
    Type: String
  ClerkClientSecret:
    Type: String
    NoEcho: true
  ClerkDomain:
    Type: String
  S3BucketName:
    Type: String
    Default: leboncoincoin-bucket

  CorsOrigins:
    Type: String
    Default: "http://localhost:5173,https://master.d1edk4x9k6kvah.amplifyapp.com"

Resources:
  LeBonCoinCoinFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: leboncoincoin-backend
      CodeUri: target/function.zip
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      AutoPublishAlias: live
      SnapStart:
        ApplyOn: PublishedVersions

      Environment:
        Variables:
          # --- Database ---
          DB_URL: !Ref DbUrl
          DB_USERNAME: !Ref DbUsername
          DB_PASSWORD: !Ref DbPassword

          # --- Clerk ---
          CLERK_AUTH_SERVER_URL: !Sub "https://${ClerkDomain}.clerk.accounts.dev"
          CLERK_ISSUER: !Sub "https://${ClerkDomain}.clerk.accounts.dev"
          CLERK_CLIENT_ID: !Ref ClerkClientId
          CLERK_CLIENT_SECRET: !Ref ClerkClientSecret

          # --- Autres ---
          S3_BUCKET_NAME: !Ref S3BucketName
          QUARKUS_PROFILE: prod

          # --- Config BDD & Flyway ---
          QUARKUS_DATASOURCE_JDBC_INITIAL_SIZE: "0"
          QUARKUS_DATASOURCE_JDBC_MIN_SIZE: "0"
          QUARKUS_DATASOURCE_JDBC_MAX_SIZE: "2"
          QUARKUS_FLYWAY_MIGRATE_AT_START: "false"

          # --- CORS ---
          CORS_ORIGINS: !Ref CorsOrigins
          QUARKUS_HTTP_CORS_ENABLED: "false"

      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"

      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"